Repository alcohol-study/2024-programmers, pull requests merged in 2024-07, with the labels that each got.

#305 [18주차] SQL : 조건에 맞는 사용자 정보 조회하기
  programmers/sql/Hong0329/조건에 맞는 사용자 정보 조회하기.sql
Labels: 홍준, 18주차😝 - 빗길 조심하세여☔️

#306 [18주차] SQL : 부서별 평균 연봉 조회하기
  programmers/sql/Hong0329/부서별 평균 연봉 조회하기.sql
Labels: 홍준, 18주차😝 - 빗길 조심하세여☔️

#307 [18주차] C++: 괄호 회전하기
  programmers/algorithm/level2/Hong0329/괄호 회전하기.cpp
Labels: 홍준, 18주차😝 - 빗길 조심하세여☔️

#308 [18주차] C++: 할인 행사
  programmers/algorithm/level2/Hong0329/할인 행사.cpp
Labels: 홍준, 18주차😝 - 빗길 조심하세여☔️

#309 [18주차] C++ : n^2 배열 자르기
  programmers/algorithm/level2/Hong0329/n^2배열 자르기.cpp
Labels: 홍준, 18주차😝 - 빗길 조심하세여☔️

#300 [18주차] SQL : 조건에 맞는 사용자 정보 조회하기
  programmers/sql/hellozo0/groupby/조건에 맞는 사용자 정보 조회하기.sql
Labels: 현주, 18주차😝 - 빗길 조심하세여☔️

#301 [18주차] SQL : 부서별 평균 연봉 조회하기
  programmers/sql/hellozo0/groupby/부서별 평균 연봉 조회하기.sql
Labels: 현주, 18주차😝 - 빗길 조심하세여☔️

#303 [18주차] JAVA : 할인 행사
  programmers/algorithm/level2/hellozo0/week18/할인행사.java
Labels: 현주, 18주차😝 - 빗길 조심하세여☔️

#304 [18주차] JAVA : n^2 배열 자르기
  programmers/algorithm/level2/hellozo0/week18/n2배열자르기.java
Labels: 현주, 18주차😝 - 빗길 조심하세여☔️

#302 [18주차] JAVA : 괄호 회전하기
  programmers/algorithm/level2/hellozo0/week18/괄호_회전하기.java
Labels: 현주, 18주차😝 - 빗길 조심하세여☔️

#310 [18주차] SQL: 조건에 맞는 사용자 정보 조회하기
  programmers/sql/sung-silver/조건에_맞는_사용자_정보_조회하기.sql
Labels: 성은💜, 18주차😝 - 빗길 조심하세여☔️

#311 [18주차] SQL: 부서별 평균 연봉 조회하기
  programmers/sql/sung-silver/부서별_평균_연봉_조회하기.sql
Labels: 성은💜, 18주차😝 - 빗길 조심하세여☔️

#312 [18주차] JAVA: 괄호 회전하기
  programmers/algorithm/level2/sung-silver/괄호_회전하기.java
Labels: 성은💜, 18주차😝 - 빗길 조심하세여☔️

#313 [18주차] JAVA: 할인 행사
  programmers/algorithm/level2/sung-silver/할인행사.java
Labels: 성은💜, 18주차😝 - 빗길 조심하세여☔️

#314 [18주차] JAVA: n^2 배열 자르기
  programmers/algorithm/level2/sung-silver/n^2_배열_자르기.java
Labels: 성은💜, 18주차😝 - 빗길 조심하세여☔️

#315 [19주차] SQL : 자동차 대여 기록 중에서 대여중 / 대여가능 여부 구분하기
  programmers/sql/hellozo0/date/자동차 대여 기록 중에서 대여중 대여가능 여부 구분하기.sql
Labels: 현주, 19주차

#316 [19주차] SQL : 대장균의 크기에 따라 분류하기 1
  programmers/sql/hellozo0/case/대장균의 크기에 따라 분류하기 1.sql
Labels: 현주, 19주차

#317 [19주차] JAVA : 행렬의 곱셈
  programmers/algorithm/level2/hellozo0/week19/행렬의곱셈.java
Labels: 현주, 19주차

#318 [19주차] JAVA : 의상
  programmers/algorithm/level2/hellozo0/week19/의상.java
Labels: 현주, 19주차

#319 //[19주차] JAVA : H-Index
  programmers/algorithm/level2/hellozo0/week19/H_Index.java
Labels: 현주, 19주차

#321 [19주차] SQL: 자동차 대여 기록에서 대여중/대여 가능 여부 구분하기
  programmers/sql/sung-silver/자동차_대여_기록_중_에서_대여중_대여가능_여부_구분하기.sql
Labels: 성은💜, 19주차

#322 [19주차] SQL: 대장균의 크기에 따라 분류하기 1
  programmers/sql/sung-silver/대장균의_크이에_따라_분류하기1.sql
Labels: 성은💜, 19주차

#323 [19주차] JAVA: 행렬의 곱셈
  programmers/algorithm/level2/sung-silver/행렬의_곱셈.java
Labels: 성은💜, 19주차

#324 [19주차] SQL : 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
  programmers/sql/Hong0329/자동차 대여 기록에서 대여중대여 가능 여부 구분하기.sql
Labels: 홍준, 19주차

#325 [19주차] JAVA: 의상
  programmers/algorithm/level2/sung-silver/의상.java
Labels: 성은💜, 19주차

#326 [19주차] SQL : 대장균의 크기에 따라 분류하기 1
  programmers/sql/Hong0329/대장균의 크기에 따라 분류하기 1.sql
Labels: 홍준, 19주차

#327 [19주차] C++ : 행렬의 곱셈
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/행렬의 곱셈.cpp
Labels: 홍준, 19주차

#328 [19주차] C++ : 의상
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/의상.cpp
Labels: 홍준, 19주차

#329 [19주차] C++ : H-Index
  programmers/algorithm/level2/Hong0329/H-Index.cpp
Labels: 홍준, 19주차

#330 [19주차] JAVA: H-Index
  programmers/algorithm/level2/sung-silver/H-index.java
Labels: 성은💜, 19주차

#340 [20주차] SQL : 취소되지 않은 진료 예약 조회하기
  .idea/workspace.xml
  programmers/sql/Hong0329/취소되지 않은 진료 예약 조회하기.sql
Labels: 홍준, 20주차

#339 [20주차] SQL : 서울에 위치한 식당 목록 출력하기
  programmers/sql/Hong0329/서울에 위치한 식당 목록 출력하기.sql
Labels: 홍준, 20주차

#338 [20주차] C++ : 기능개발
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/기능개발.cpp
Labels: 홍준, 20주차

#337 [20주차] C++ : 이중우선순위큐
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/이중우선순위큐.cpp
Labels: 홍준, 20주차

#336 [20주차] C++ : 캐시
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/캐시.cpp
Labels: 홍준, 20주차

#331 [20주차] JAVA : 캐시
  programmers/algorithm/level2/hellozo0/week20/캐시_정답버전.java
  programmers/algorithm/level2/hellozo0/week20/캐시_틀린버전.java
Labels: 현주, 20주차

#332 [20주차] SQL : 취소되지 않은 진료 예약 조회하기
  programmers/sql/hellozo0/date/취소되지_않은_진료_예약_조회하기.sql
Labels: 현주, 20주차

#333 [20주차] SQL : 서울에 위치한 식당 목록 출력하기
  programmers/sql/hellozo0/groupby/서울에_위치한_식당_목록_출력하기.sql
Labels: 현주, 20주차

#334 [20주차] JAVA : 이중우선순위큐
  programmers/algorithm/level2/hellozo0/week20/이중우선순위큐.java
Labels: 현주, 20주차

#335 [20주차] JAVA : 기능개발
  programmers/algorithm/level2/hellozo0/week20/기능개발.java
Labels: 현주, 20주차

#341 [21주차] SQL : 년, 월, 성별 별 상품 구매 회원 수 구하기
  programmers/sql/hellozo0/groupby/년월성별_별_상품_구매_회원수_구하기.sql
Labels: 현주, 21주차

#342 [21주차] SQL : 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
  programmers/sql/hellozo0/subQuery/조회수가_가장많은_중고거래_게시판의_첨부파일_조회하기.sql
Labels: 현주, 21주차

#347 [21주차] JAVA : 정수 삼각형
  programmers/algorithm/level2/hellozo0/week21/정수삼각형.java
Labels: 현주, 21주차

#356 [21주차] C++ : 튜플
  programmers/algorithm/level2/Hong0329/튜플.cpp
Labels: 홍준, 21주차

#357 [21주차] C++ : 정수 삼각형
  programmers/algorithm/level2/Hong0329/정수 삼각형.cpp
Labels: 홍준, 21주차

#358 [21주차] C++ : 피로도
  programmers/algorithm/level2/Hong0329/피로도.cpp
Labels: 홍준, 21주차

#359 [21주차] SQL : 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
  .idea/workspace.xml
  programmers/sql/Hong0329/조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기.sql
Labels: 홍준, 21주차

#360 [21주차] SQL : 년, 월, 성별 별 상품 구매 회원 수 구하기
  programmers/sql/Hong0329/년, 월, 성별 별 상품 구매 회원 수 구하기.sql
Labels: 홍준, 21주차

#344 [20주차] JAVA: [1차] 캐시
  programmers/algorithm/level2/sung-silver/1차_캐시.java
Labels: 성은💜, 20주차

#345 [20주차] SQL: 취소되지 않은 진로 예약 조회하기
  programmers/sql/sung-silver/취소하지_않은_예약_조회하기.sql
Labels: 성은💜, 20주차

#346 [20주차] SQL: 서울에 위치한 식당 목록 출력하기
  programmers/sql/sung-silver/서울에_위치한_식당_목록_출력하기.sql
Labels: 성은💜, 20주차

#349 [20주차] JAVA: 이중우선순위큐
  programmers/algorithm/level2/sung-silver/이중우선순위큐.java
Labels: 성은💜, 20주차

#350 [20주차] JAVA: 기능개발
  programmers/algorithm/level2/sung-silver/기능개발.java
Labels: 성은💜, 20주차

#351 [21주차] SQL: 년,월,성별 별 상품 구매 회원 수 구하기
  programmers/sql/sung-silver/년_월_성별_별_상품_구매_회원_수_구하기.sql
Labels: 성은💜, 21주차

#352 [21주차] SQL: 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
  programmers/sql/sung-silver/조회수가_가장_많은_중고거래_게시판의_첨부파일_조회하기.sql
Labels: 성은💜, 21주차

#353 [21주차] JAVA: 튜플
  programmers/algorithm/level2/sung-silver/튜플.java
Labels: 성은💜, 21주차
