Repository alcohol-study/2024-programmers, pull requests merged in 2024-08, with the labels that each got.

#375 [22주차] C++ : 네트워크
  .idea/workspace.xml
  programmers/algorithm/level3/Hong0329/네트워크.cpp
Labels: 홍준, 22주차

#376 [22주차] C++ : 프로세스
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/프로세스.cpp
Labels: 홍준, 22주차

#378 [22주차] SQL: 우유와 요거트가 담긴 장바구니
  programmers/sql/Hong0329/우유와 요거트가 담긴 장바구니.sql
Labels: 홍준, 22주차

#379 [22주차] SQL : 저자 별 카테고리 별 매출액 집계하기
  programmers/sql/Hong0329/저자 별 카테고리 별 매출액 집계하기.sql
Labels: 홍준, 22주차

#361 [22주차] SQL : 저자 별 카테고리 별 매출액 집계하기
  programmers/sql/hellozo0/join/저자별_카테고리별_매출액_집계하기.sql
Labels: 현주, 22주차

#363 [22주차] JAVA : 프로세스
  programmers/algorithm/level2/hellozo0/week22/프로세스.java
Labels: 현주, 22주차

#362 [22주차] SQL : 우유와 요거트가 담긴 장바구니
  programmers/sql/hellozo0/union/우유와_요거트가_담긴_장바구니
Labels: 현주, 22주차

#368 [22주차] JAVA: 프로세스
  programmers/algorithm/level2/sung-silver/프로세스.java
Labels: 성은💜, 22주차

#369 [22주차] SQL: 저자 별 카테고리 별 매출액 집계하기
  programmers/sql/sung-silver/저자_별_카테고리_별_매출액_집계하기.sql
Labels: 성은💜, 22주차

#370 [22주차] SQL: 우유와 요거트가 담긴 장바구니
  programmers/sql/sung-silver/우유와_요거트가_담긴_장바구니.sql
Labels: 성은💜, 22주차

#371 [22주차] JAVA: [1차] 뉴스 클러스터링
  programmers/algorithm/level2/sung-silver/1차_뉴스_클러스터링.java]
Labels: 성은💜, 22주차

#373 [22주차] JAVA: 네트워크
  programmers/algorithm/level3/sung-silver/네트워크.java
Labels: 성은💜, 22주차

#380 [23주차] SQL : 헤비 유저가 소유한 장소
  programmers/sql/hellozo0/subQuery/헤비유저가소유장소.sql
Labels: 현주, 23주차

#381 [23주차] SQL : 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
  programmers/sql/hellozo0/subQuery/대여_횟수가_많은_자동차들의_월별_대여_횟수_구하기.sql
Labels: 현주, 23주차

#382 [23주차] JAVA : 전화번호 목록
  programmers/algorithm/level2/hellozo0/week23/전화번호목록.java
Labels: 현주, 23주차

#383 [23주차] JAVA : 타겟 넘버
  programmers/algorithm/level2/hellozo0/week23/타겟넘버.java
Labels: 현주, 23주차

#384 [23주차] JAVA : 야근 지수
  programmers/algorithm/level3/hellozo0/week23/야근지수.java
Labels: 현주, 23주차

#385 [23주차] SQL: 헤비 유저가 소유한 장소
  programmers/sql/sung-silver/헤비_유저가_소유한_장소.sql
Labels: 성은💜, 23주차

#386 [23주차] SQL: 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
  programmers/sql/sung-silver/대여_횟수가_많은_자동차들의_월별_대여_횟수_구하기.sql
Labels: 성은💜, 23주차

#387 [23주차] JAVA: 전화번호 목록
  programmers/algorithm/level2/전화번호_목록.java
Labels: 성은💜, 23주차

#388 [23주차] JAVA: 타겟 넘버
  programmers/algorithm/level2/타겟_넘버.java
Labels: 성은💜, 23주차

#389 [23주차] JAVA: 야근 지수
  programmers/algorithm/level3/야근_지수.java
Labels: 성은💜, 23주차

#390 [23주차] SQL : 헤비 유저가 소유한 장소
  .idea/workspace.xml
  programmers/sql/Hong0329/헤비 유저가 소유한 장소.sql
Labels: 홍준, 23주차

#391 [23주차] SQL : 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
  programmers/sql/Hong0329/대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기.sql
Labels: 홍준, 23주차

#392 [23주차] C++ : 전화번호 목록
  programmers/algorithm/level2/Hong0329/전화번호 목록.cpp
Labels: 홍준, 23주차

#393 [23주차] C++ : 타겟 넘버
  programmers/algorithm/level2/Hong0329/타겟 넘버.cpp
Labels: 홍준, 23주차

#394 [23주차] C++ : 야근 지수
  programmers/algorithm/level3/Hong0329/야근 지수.cpp
Labels: 홍준, 23주차

#396 [24주차] SQL: 그룹별 조건에 맞는 식당 목록 출력하기
  programmers/sql/sung-silver/그룹별_조건에_맞는_식당_목록_출력하기.sql
Labels: 성은💜, 24주차

#403 [24주차] JAVA: K진수에서 소수 개수 구하기
  programmers/algorithm/level2/sung-silver/k진수에서_소수_개수_구하기.java
Labels: 성은💜, 24주차

#405 [24주차] SQL: 주문량이 많은 아이스크림들 조회하기
  programmers/sql/Hong0329/주문량이 많은 아이스크림들 조회하기.sql
Labels: 홍준, 24주차

#406 [24주차] SQL: 그룹별 조건에 맞는 식당 목록 출력하기
  programmers/sql/Hong0329/그룹별 조건에 맞는 식당 목록 출력하기.sql
Labels: 홍준, 24주차

#407 [24주차] C++ : [3차] n진수 게임
  programmers/algorithm/level2/Hong0329/[3차] n진수 게임.cpp
Labels: 홍준, 24주차

#408 [24주차] C++ : k진수에서 소수 개수 구하기
  .idea/workspace.xml
  programmers/algorithm/level2/Hong0329/k진수에서 소수 개수 구하기.cpp
Labels: 홍준, 24주차

#409 [24주차] C++ : 단어 변환
  programmers/algorithm/level3/Hong0329/단어 변환.cpp
Labels: 홍준, 24주차

#401 [24주차] JAVA : 단어 변환
  programmers/algorithm/level3/hellozo0/week24/단어변환.java
Labels: 현주, 24주차

#400 [24주차] JAVA : k진수에서 소수 개수 구하기
  programmers/algorithm/level2/hellozo0/week24/k진수에서_소수_개수_구하기.java
Labels: 현주, 24주차

#399 [24주차] JAVA : [3차] n진수 게임
  programmers/algorithm/level2/hellozo0/week24/n진수_게임.java
Labels: 현주, 24주차

#398 [24주차] SQL : 그룹별 조건에 맞는 식당 목록 출력하기
  programmers/sql/hellozo0/join/그룹별_조건에_맞는_식당_목록_출력하기.sql
Labels: 현주, 24주차

#397 [24주차] SQL : 주문량이 많은 아이스크림들 조회하기
  programmers/sql/hellozo0/join/주문량이_많은_아이스크림들_조회하기.sql
Labels: 현주, 24주차

#416 [25주차] JAVA : [3차] 압축
  programmers/algorithm/level2/hellozo0/week25/압축.java
Labels: 현주, 25주차

#415 [25주차] JAVA : 등굣길
  programmers/algorithm/level3/hellozo0/week25/등굣길.java
Labels: 현주, 25주차

#412 [25주차] JAVA : 게임 맵 최단거리
  programmers/algorithm/level2/hellozo0/week25/게임_맵_최단거리.java
Labels: 현주, 25주차

#411 [25주차] SQL : 연간 평가점수에 해당하는 등급 및 성과금 조회하기
  programmers/sql/hellozo0/case/연간_평가점수에_해당하는_등급_및_성과금_조회하기.sql
Labels: 현주, 25주차

#410 [25주차] SQL : 대장균들의 자식의 수 구하기
  programmers/sql/hellozo0/subQuery/대장균들의_자식의_수_구하기.sql
Labels: 현주, 25주차
