Repository alcohol-study/2024-programmers, pull requests merged in 2024-06, with the labels that each got.

#229 [14주차] SQL : 오랜 기간 보호한 동물(2)
  programmers/sql/hellozo0/join/오랜_기간_보호한_동물2.sql
Labels: 현주, 14주차

#230 [14주차] SQL : 보호소에서 중성화한 동물
  programmers/sql/hellozo0/like/보호소에서_중성화한_동물.sql
Labels: 현주, 14주차

#231 [14주차] JAVA : 다음 큰 숫자
  programmers/algorithm/level2/hellozo0/week14/다음_큰_숫자.java
Labels: 현주, 14주차

#232 [14주차] JAVA : 피보나치 수
  programmers/algorithm/level2/hellozo0/week14/피보나치_수.java
Labels: 현주, 14주차

#233 [14주차] JAVA : 짝지어 제거하기
  programmers/algorithm/level2/hellozo0/week14/짝지어_제거하기.java
Labels: 현주, 14주차

#234 [14주차] SQL: 오랜 기간 보호한 동물(2)
  programmers/sql/sung-silver/오랜_기간_보호한_동물_2.sql
Labels: 성은💜, 14주차

#235 [14주차] SQL: 보호소에서 중성화한 동물
  programmers/sql/sung-silver/보호서에서_중성화한_동물.sql
Labels: 성은💜, 14주차

#236 [14주차] JAVA: 다음 큰 숫자
  programmers/algorithm/level2/sung-silver/다음_큰_숫자.java
Labels: 성은💜, 14주차

#237 [14주차] JAVA: 피보나치 수
  programmers/algorithm/level2/sung-silver/피보나치_수.java
Labels: 성은💜, 14주차

#238 [14주차] JAVA: 짝지어 제거하기
  programmers/algorithm/level2/sung-silver/짝지어_제거하기.java
Labels: 성은💜, 14주차

#239 [14주차] SQL : 오랜 기간 보호한 동물(2)
  programmers/sql/Hong0329/오랜 기간 보호한 동물(2).sql
Labels: 홍준, 14주차

#240 [14주차] SQL : 보호소에서 중성화한 동물
  programmers/sql/Hong0329/보호소에서 중성화한 동물.sql
Labels: 홍준, 14주차

#241 [14주차] C++ : 다음 큰 숫자
  programmers/algorithm/level2/Hong0329/다음 큰 숫자.cpp
Labels: 홍준, 14주차

#242 [14주차] C++ : 피보나치 수
  programmers/algorithm/level2/Hong0329/피보나치 수.cpp
Labels: 홍준, 14주차

#243 [14주차] C++ : 짝지어 제거하기
  programmers/algorithm/level2/Hong0329/짝지어 제거하기.cpp
Labels: 홍준, 14주차

#244 [14주차] Kotlin: 짝지어제거하기.kt
  programmers/algorithm/level2/unanchoi/짝지어제거하기.java
Labels: 유난, 14주차

#245 [14주차] Kotlin: 피보나치수
  programmers/algorithm/level2/unanchoi/피보나치수.kt
Labels: 유난, 14주차

#246 [14주차] Java: 다음큰숫자.java
  programmers/unanchoi/lv2/다음큰숫자.java
Labels: 유난, 14주차

#247 [14주차] SQL: 조건별로 분류하여 주문상태 출력하기
  programmers/sql/unanchoi/조건별로분류하여주문상태출력하기.sql
Labels: 유난, 14주차

#249 [15주차] SQL: 대여 기록이 존재하는 자동차 리스트 구하기
  programmers/sql/sung-silver/대여_기록이_존재하는_자동차_리스트_구하기.sql
Labels: 성은💜, 15주차

#250 [15주차] SQL: 조건에 맞는 사용자와 총 거래금액 조회하기
  programmers/sql/sung-silver/조건에_맞는_사용자와_총_거래금액_조회하기.sql
Labels: 성은💜, 15주차

#251 [15주차] SQL : 대여 기록이 존재하는 자동차 리스트 구하기
  programmers/sql/hellozo0/date/대여_기록이_존재하는_자동차_리스트_구하기.sql
Labels: 현주, 15주차

#252 [15주차] SQL : 조건에 맞는 사용자와 총 거래금액 조회하기
  programmers/sql/hellozo0/groupby/조건에_맞는_사용자와_총_거래금액_조회하기.sql
Labels: 현주, 15주차

#253 [15주차] JAVA : 카펫
  programmers/algorithm/level2/hellozo0/week15/카펫.java
Labels: 현주, 15주차

#255 [15주차] JAVA : 점프와 순간 이동
  programmers/algorithm/level2/hellozo0/week15/점프와_순간_이동.java
Labels: 현주, 15주차

#256 [15주차] JAVA: 카펫
  programmers/algorithm/level2/sung-silver/카펫.java
Labels: 성은💜, 15주차

#257 [15주차] SQL : 대여_기록이_존재하는_자동차_리스트_구하기
  programmers/sql/unanchoi/대여_기록이_존재하는_자동차_리스트_구하기.md
Labels: 유난, 15주차

#258 [15주차] Java : 점프와순간이동.java
  programmers/algorithm/level2/unanchoi/점프와순간이동.java
Labels: 유난, 15주차

#259 [15주차] Kotlin: 카펫.kt
  programmers/unanchoi/lv2/카펫.kt
Labels: 유난, 15주차

#261 [15주차] Java: N개의최소공배수.java
  programmers/algorithm/level2/unanchoi/N개의최소공배수.java
Labels: 유난, 15주차

#262 [15주차] SQL : 대여 기록이 존재하는 자동차 리스트 구하기
  programmers/sql/Hong0329/대여 기록이 존재하는 자동차 리스트 구하기.sql
Labels: 홍준, 15주차

#263 [15주차] SQL : 조건에 맞는 사용자와 총 거래금액 조회하기
  programmers/sql/Hong0329/조건에 맞는 사용자와 총 거래금액 조회하기.sql
Labels: 홍준, 15주차

#264 [15주차] C++ : 카펫
  programmers/algorithm/level2/Hong0329/카펫.cpp
Labels: 홍준, 15주차

#266 [15주차] C++ : N개의 최소공배수
  programmers/algorithm/level2/Hong0329/N개의 최소공배수.cpp
Labels: 홍준, 15주차

#268 [15주차] JAVA: N개의 최소공배수
  programmers/algorithm/level2/sung-silver/N개의_최소공배수.java
Labels: 성은💜, 15주차

#280 [16주차] SQL : 식품분류별 가장 비싼 식품의 정보 조회하기
  programmers/sql/Hong0329/식품분류별 가장 비싼 식품의 정보 조회하기.sql
Labels: 홍준, 16주차

#281 [16주차] SQL : 5월 식품들의 총매출 조회하기
  programmers/sql/Hong0329/5월 식품들의 총매출 조회하기 .sql
Labels: 홍준, 16주차

#282 [16주차] C++ : 예상 대진표
  programmers/algorithm/level2/Hong0329/예상 대진표.cpp
Labels: 홍준, 16주차

#283 [16주차] C++ : 구명보트
  programmers/algorithm/level2/Hong0329/구명보트.cpp
Labels: 홍준, 16주차

#284 [16주차] C++ : 멀리 뛰기
  programmers/algorithm/level2/Hong0329/멀리 뛰기.cpp
Labels: 홍준, 16주차

#270 [16주차] SQL : 5월 식품들의 총매출 조회하기
  programmers/sql/hellozo0/groupby/5월_식품들의_총매출_조회하기.sql
Labels: 현주, 16주차

#271 [16주차] SQL : 식품분류별 가장 비싼 식품의 정보 조회하기
  programmers/sql/hellozo0/groupby/식품_분류별_가장_비싼_식품의_정보_조회하기.sql
Labels: 현주, 16주차

#272 [16주차] SQL: 식품분류별 가장 비싼 식품의 정보 조회하기
  programmers/sql/sung-silver/식품분류별_가장_비싼_식품의_정보_조회하기.sql
Labels: 성은💜, 16주차

#273 [16주차] SQL: 5월 식품들의 총매출 조회하기
  programmers/sql/sung-silver/5월_식품들의_총매출_조회하기.sql
Labels: 성은💜, 16주차

#274 [16주차] JAVA : 구명보트
  programmers/algorithm/level2/hellozo0/week16/구명보트.java
Labels: 현주, 16주차

#275 [16주차] JAVA : 예상 대진표
  programmers/algorithm/level2/hellozo0/week16/예상_대진표.java
Labels: 현주, 16주차

#276 [16주차] JAVA : 멀리 뛰기
  programmers/algorithm/level2/hellozo0/week16/멀리뛰기.java
Labels: 현주, 16주차

#277 [16주차] JAVA: 구명보트
  programmers/algorithm/level2/sung-silver/구명보트.java
Labels: 성은💜, 16주차

#278 [16주차] JAVA: 멀리 뛰기
  programmers/algorithm/level2/sung-silver/멀리뛰기.java
Labels: 성은💜, 16주차

#279 [16주차] JAVA: 예상 대진표
  programmers/algorithm/level2/sung-silver/예상_대진표.java
Labels: 성은💜, 16주차

#285 [17주차] SQL : 즐겨찾기가 가장 많은 식당 정보 출력하기
  programmers/sql/hellozo0/groupby/즐겨찾기가_가장_많은_식당_정보_출력하기.sql
Labels: 현주, 17주차

#286 [17주차] SQL : 없어진 기록 찾기
  programmers/sql/hellozo0/join/없어진_기록_찾기.sql
Labels: 현주, 17주차

#287 [17주차] JAVA : 영어 끝말잇기
  programmers/algorithm/level2/hellozo0/week17/영어_끝말잇기.java
Labels: 현주, 17주차

#288 [17주차] JAVA : 귤 고르기
  programmers/algorithm/level2/hellozo0/week17/귤_고르기.java
Labels: 현주, 17주차

#289 [17주차] SQL: 즐겨찾기가 가장 많은 식당 정보 출력하기
  programmers/sql/sung-silver/즐겨찾기가_가장_많은_식당_정보_출력하기.sql
Labels: 성은💜, 17주차

#290 [17주차] SQL: 없어진 기록 찾기
  programmers/sql/sung-silver/없어진_기록_찾기.sql
Labels: 성은💜, 17주차

#291 [17주차] JAVA: 영어 끝말잇기
  programmers/algorithm/level2/sung-silver/영어_끝말잇기.java
Labels: 성은💜, 17주차

#292 [17주차] JAVA: 귤 고르기
  programmers/algorithm/level2/sung-silver/귤_고르기.java
Labels: 성은💜, 17주차

#293 [17주차] JAVA: 연속 부분 합의 개수
  programmers/algorithm/level2/sung-silver/연속_부분_수열_합의_개수.java
Labels: 성은💜, 17주차

#294 [17주차] sql : 즐겨찾기가 가장 많은 식당 정보 출력하기
  programmers/sql/Hong0329/즐겨찾기가 가장 많은 식당 정보 출력하기.sql
Labels: 홍준, 17주차

#295 [17주차] sql : 없어진 기록 찾기
  programmers/sql/Hong0329/없어진 기록 찾기.sql
Labels: 홍준, 17주차

#296 [17주차] C++ : 영어 끝말잇기
  programmers/algorithm/level2/Hong0329/영어 끝말잇기.cpp
Labels: 홍준, 17주차

#297 [17주차] C++ : 귤 고르기
  programmers/algorithm/level2/Hong0329/귤 고르기.cpp
Labels: 홍준, 17주차

#298 [17주차] C++ : 연속 부분 합의 개수
  programmers/algorithm/level2/Hong0329/연속 부분 합의 개수.cpp
Labels: 홍준, 17주차

#299 [17주차] JAVA : 연속 부분 수열 합의 개수
  programmers/algorithm/level2/hellozo0/week17/연속_부분_수열_합의_개수.java
Labels: 현주, 17주차
